### PR TITLE
Implement flow control (burst hertz, drop)

### PR DESCRIPTION
**Pull request by Artoria2e5**
Is that what it should look like? And then we need to have a queue to hold them so we are only throttling..

### CODE REVIEW

**Comment by gumblex** [comment]
You've found the wrong function. It should be `irc_forward`. :new_moon_with_face:

**Comment by Arthur2e5** [comment]
:new_moon_with_face:

**Comment by Artoria2e5** [comment]
I thought all speech should be controlled :new_moon_with_face:

**Comment by gumblex** [comment]
Then you should wrap `ircconn.say`. :full_moon_with_face:

**Comment by Artoria2e5** [comment]
:new_moon_with_face: Bucket kicked.

**Pull request merged**
